[target.'cfg(target_os = "linux")']
rustflags = ["-C", "link-arg=-nostartfiles"]

[target.'cfg(target_os = "windows")']
rustflags = ["-C", "link-args=/ENTRY:_start /SUBSYSTEM:console"]

# -e __start – тут мы задаём начальную функцию как _start
# дополнительный символ _ необходим так как в макоси все функции начинаются с _
#
# -static – макось официально не поддерживает статически связанные бинарники
# чтобы изменить это поведение нужно явно передать флаг -static
#
# -nostartfiles – необходим чтоы отвязаться от crt0 (C runtime Zero)
[target.'cfg(target_os = "macos")']
rustflags = ["-C", "link-args=-e __start -static -nostartfiles"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"